### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by mishashevelinn** [mishashevelinn/chess#1]
https://github.com/mishashevelinn/chess/blob/ace72dd1f883cdb4e2a89bdb07b452def7388d2e/Board.cpp#L24
Allocating with `new [ ]` isn't followed by any `delete [ ]`.
Adding a distractor, containing following line:
`delete [ ] board`
leads to bad free() error while testing on remote server.
without a distructor passing all tests.

**Comment by Abziz** [comment]
The problem lies within this assignment.
https://github.com/mishashevelinn/chess/blob/ace72dd1f883cdb4e2a89bdb07b452def7388d2e/Board.cpp#L185
There's no user defined copy assignment operator, so the compiler will generate a default assignment operator, that shallow copies the fields, among them is the `Square ** board` member.
That's exactly where the rule of three (Big three) comes in.

**Comment by mishashevelinn** [comment]
I think now I can see what's happening:
https://github.com/mishashevelinn/chess/blob/ace72dd1f883cdb4e2a89bdb07b452def7388d2e/Board.cpp#L175-185

**Comment by mishashevelinn** [comment]
I think now I can see what's happening:
By the moment https://github.com/mishashevelinn/chess/blob/ace72dd1f883cdb4e2a89bdb07b452def7388d2e/Board.cpp#L175
comes to closing brackets, destructor called to delete local shellow copied variable `backup`
https://github.com/mishashevelinn/chess/blob/ace72dd1f883cdb4e2a89bdb07b452def7388d2e/Board.cpp#L176
but `backup`'s filed now points to the same array as `this`'s and destructor clears it as well.
Do I describe a stiuation right?

**Comment by Abziz** [comment]
exactly.
